listen=YES 
max_clients=3 
max_per_ip=1 
pasv_min_port=65500 
pasv_max_port=65535 
local_enable=YES 
local_root=/var/ftp/private 
ftpd_banner=Banner_Welcome 
dirmessage_enable=YES 
xferlog_enable=YES 
connect_from_port_20=YES 
secure_chroot_dir=/usr/local/share/vsftpd/empty 
background=YES 
# If no anonymous access 
anonymous_enable=NO 
# If anonymous access 
anon_root=/var/ftp/public 
no_anon_password=NO 
