[debianhosts]
172.20.240.2 ansible_user=dawg ansible_become_pass=Ch@ng3_m3 ansible_ssh_pass=Ch@ng3_m3
172.20.242.1 ansible_user=dawg ansible_become_pass=Ch@ng3_m3 ansible_ssh_pass=Ch@ng3_m3

[rhelhosts]
172.20.241.10
